### ISSUE TITLE
Are named accross a few organization supported?

### ISSUE THREAD

**Issue by mate201** [vmware/cloud-director-named-disk-csi-driver#195]
My manually installed Kubernetes cluster needs to be spread across vdcs. Does this module support it? I understand that named disks can't be moved, but pods can be stitched to some specific vdc.

**Comment by JSN-1** [comment]
i would like to know this as well, please respond. 

Thanks

**Comment by arunmk** [comment]
The Infrastructure Provider (VMware Cloud Director) does not support this

**Comment by arunmk** [comment]
> My manually installed Kubernetes cluster needs to be spread across vdcs. Does this module support it? I understand that named disks can't be moved, but pods can be stitched to some specific vdc.

The infrastructure provider (VMware Cloud Provider) does not support storage that is accessible across VDCs or across Organizations.
