### ISSUE TITLE
Cannot mount disk into host directory because diskUUID is empty string

### ISSUE THREAD

**Issue by phongvu0403** [vmware/cloud-director-named-disk-csi-driver#21]
### Describe the bug

Hi everyone, I know vCD API version and vCD installation version which is support by this CSI. But my vCD infrastructure version is 10.2 and API version is 35.0. We will upgrade vCD in the near future. I changed this source code a little (vcdclient only authenticate with vCD by user/pass, API version constraint is >= 35.0, don't use CSE extension). But I am facing the error `diskUUID should not be an empty string` when describing test pod (I use my-pvc.yaml and pvc-debugger.yaml in samples directory). I wrote a test file under pkg/vcdclient directory:
```
/*
   Copyright 2021 VMware, Inc.
   SPDX-License-Identifier: Apache-2.0
*/

package vcdclient

import (
	"fmt"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
)

func Test1(t *testing.T) {

	// get client
	vcdClient, err := getTestVCDClient(map[string]interface{}{
		"getVdcClient": true,
	})
	if err != nil {
		panic(err)
	}
	_, err = vcdClient.vdc.FindStorageProfileReference("Premium-SSD")

	if err != nil {
		fmt.Errorf("cannot get storage profile Premium-SSD")
	}


	diskName := fmt.Sprintf("test-pvc-%s", uuid.New().String())
	disk, err := vcdClient.CreateDisk(diskName, 100, VCDBusTypeSCSI, VCDBusSubTypeVirtualSCSI,
		"", "Premium-SSD", false)
	if err != nil {
		fmt.Errorf("cannot create disk")
	}
	fmt.Println("UUID of disk is")
	fmt.Println(disk.UUID)
	fmt.Println("ID of disk is")
	fmt.Println(disk.Id)
	fmt.Println("Shareable of disk is")
	fmt.Println(disk.Shareable)
	fmt.Println()

	// get VM
	nodeID := "fke-worker1"
	vm, err := vcdClient.FindVMByName(nodeID)
	require.NoError(t, err, "unable to find VM [%s] by name", nodeID)
	require.NotNil(t, vm, "vm should not be nil")
	if err != nil {
		fmt.Errorf("cannot find VM by name")
	}
	vcdClient.AttachVolume(vm, disk)
	vcdClient.govcdAttachedVM(disk)
	vcdClient.DetachVolume(vm, disk.Name)
	vcdClient.DeleteDisk(diskName)

	return
}
```

Then I performed `make test` command. And this is output of Test1 function:
```
=== RUN   Test1
UUID of disk is

ID of disk is
urn:vcloud:disk:3b9c03c8-5a40-45f8-abe8-ae727c4bede2
Shareable of disk is
false

--- PASS: Test1 (39.56s)
```
UUID value of disk is empty.
Is that a error caused by version of vCD API and vCD Installation? What features of vCD API version 36.0 this code used?
Thanks in advanced!

### Reproduction steps

```bash
1. Change this source a little (as mentioned) (vCD API version 35.0, vCD Installation 10.2)
2. Facing this error
3.
...
```

### Expected behavior

Can get UUID of disk

### Additional context

Can you need some information about my issue?

**Comment by arunmk** [comment]
@phongvu0403 apologies for the delayed response. We need 10.3.0 as a minimum version of VCD. This is because 10.3.0 (API v36.0) has a specific change that allows us to get the disk UUID using VCD API. Earlier versions of VCD do not have the change.

Also note that 10.3.1 is the version officially supported, since 10.3.1 brings refresh-token based login. That is the recommended and secure way of using CSI.
