### ISSUE TITLE
Duplicate Authorization headers cause requests to fail when vCD is behind L7 load balancers

### ISSUE THREAD

**Issue by an0nz** [vmware/cloud-director-named-disk-csi-driver#26]
### Describe the bug

As per the bugs raised in https://github.com/vmware/go-vcloud-director/issues/425 and https://github.com/vmware/cloud-provider-for-cloud-director/issues/37, when vCD is behind an L7 Load Balancer authentication fails due to duplicate Authorization headers being sent.

Only 1 Authorization header can be sent else it is an invalid request.

### Reproduction steps

```bash
1. Place vCD behind an L7 load balancer such as NSX-ALB (Avi)
2. Attempt to use the CSI driver with vCD
```

### Expected behavior

Communication to the vCD API works behind an L7 Load Balancer

**Comment by arunmk** [comment]
@Anirudh9794 will bring this in along with the mirror bug in CPI and CAPVCD.
