### ISSUE TITLE
Unable to mount the PVC to the pod in RKE cluster

### ISSUE THREAD

**Issue by balajivedagiri** [vmware/cloud-director-named-disk-csi-driver#44]
### Describe the bug

Hi,

I am able to install the driver on RKE cluster and provision the PVC but mounting it to the POD has failed with below error

MountVolume.MountDevice failed for volume "pvc-fd87939e-f5b2-40c8-a842-0b868eec4511" : rpc error: code = Internal desc = unable to format and mount device [] at path [/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-fd87939e-f5b2-40c8-a842-0b868eec4511/globalmount] with fs [[rw]] and flags [exit status 32]: [%!!(MISSING)!(MISSING)v(MISSING)]

Unable to attach or mount volumes: unmounted volumes=[testpvc], unattached volumes=[testpvc kube-api-access-6mbqt]: timed out waiting for the condition

Regards,
Balaji

### Reproduction steps

```bash
1.Install all the manifest files on the vanila cluster or RKE cluster
2. Install the driver
3. Create the PVC
4. Create a deployment pod with PVC
...
```

### Expected behavior

Below are the errors in the container log

MountVolume.MountDevice failed for volume "pvc-fd87939e-f5b2-40c8-a842-0b868eec4511" : rpc error: code = Internal desc = unable to format and mount device [] at path [/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-fd87939e-f5b2-40c8-a842-0b868eec4511/globalmount] with fs [[rw]] and flags [exit status 32]: [%!!(MISSING)!(MISSING)v(MISSING)]

Unable to attach or mount volumes: unmounted volumes=[testpvc], unattached volumes=[testpvc kube-api-access-6mbqt]: timed out waiting for the condition

**Comment by arunmk** [comment]
@balajivedagiri this is happening because the device name could not be found. We need a minimum VCD version of 10.3.1 in order to run CSI since it depends on a new API which will provide the device UUID (that is translated to the name). Could you confirm that you are running against that VCD?

**Comment by arunmk** [comment]
Actually @balajivedagiri , since you created the cluster yourself, I think you may not have the set the `disk.enableUUID` variable in the ExtraConfig section of the VM. If you create a cluster using CSE that is already set up.

When this variable is set, there is a UUID that is attached to the disk that can be detected by CSI. CSI creates a disk and then uses this UUID to know what the disk is attached as on the host VM.

If you want to use RKE and try it out, use `govc` to enable this variable on all worker nodes.

**Comment by balajivedagiri** [comment]
Hi Arun,
Thanks for highlighting, i don't know how i missed it. I thought i set the"disk.enableUUID" parameter on template when i was testing another cluster with vsphere csi driver .

Thanks again. The vcloud CSI driver is working now.

Regards,
Balaji

**Comment by balajivedagiri** [comment]
@arunmk 
Thanks for highlighting, i don't know how i missed it. I thought i set the"disk.enableUUID" parameter on template when i was testing another cluster with vsphere csi driver .

Thanks again. The vcloud CSI driver is working now.

Regards,
Balaji

**Comment by erdembas** [comment]
The disk UUID does not appear even though there is a definition as below on the virtual machine. What could be the reason? Is disk.enableUUID case sensitive? Does the setting need to be capital E like disk.EnableUUID?

![CleanShot 2022-05-31 at 00 59 32](https://user-images.githubusercontent.com/2093046/171062992-b5510084-1703-4878-b2aa-a85d6a35fef1.png)

Thank you

**Comment by arunmk** [comment]
@erdembas are you using a VCloud Director of version 10.3.0 and above? There was a change made in 10.3.0 to support getting the disk UUID from VCD API.
